current_workflow = "MODE-A"
current_step = "implement-sdd"
workflow_run_id = "4594c98e"
test_command = "cargo test"
lint_command = "cargo clippy"
build_command = "cargo build --release"
test_unit_command = "cargo test --lib"
test_integration_command = "cargo test --test integration"
step_history = [ "req-create", "req-approve", "brainstorm", "write-plan", "implement-sdd", "code-review", "test-run", "verify", "req-create", "req-approve", "brainstorm", "write-plan", "implement-sdd", "code-review", "test-run", "verify", "req-create", "req-approve", "brainstorm", "write-plan", "implement-sdd", "code-review", "test-run", "verify", "req-create", "req-approve", "brainstorm", "write-plan", "implement-sdd", "code-review", "test-run", "verify", "finish", "finish", "req-create", "req-approve", "brainstorm", "write-plan", "finish", "req-create", "req-approve", "brainstorm", "write-plan", "finish", "req-create", "req-approve", "brainstorm", "write-plan",]
approved_items = [ "CODE-REVIEW-79b17a86", "CODE-REVIEW-38f782cc", "CODE-REVIEW-3bc87e1a",]
